### ISSUE TITLE
Can't select dropdown with touchscreen

### ISSUE THREAD

**Issue by courtneysimonse** [courtneysimonse/pilgrimage-cincinnati#2]
When I try out my map on a touchscreen, I can't use the trail selector dropdown. Do I need to use a different kind of element or is there some kind of option I should be using?

**Comment by courtneysimonse** [comment]
Well, maybe it's just a Firefox Web Developer Tools issue - it works fine on my phone.

**Comment by rgdonohue** [comment]
Yeah, unfortunately the mobile emulators in a browser are only so good.
